### ISSUE TITLE
Doesn't seem to work with SQL Azure

### ISSUE THREAD

**Issue by joewood** [DickvdBrink/vscode-sql-connect#1]
Could you add a parameter to specify that encrypted connection is required for SQL Azure?

**Comment by DickvdBrink** [comment]
Thanks for filing this issue.
Will try to update the extension in the gallery tonight but not sure if I can make it

**Comment by DickvdBrink** [comment]
Took me a bit longer then expected - but published it a few minutes ago :) Thanks
